### ISSUE TITLE
How to make the script stay running listening for hotkeys?

### ISSUE THREAD

**Issue by kizzard** [mkzeender/autohotpy#1]
Love the idea behind this module. Super cool.

When I create a Python script with a simple hotkey decorated function and run it, python runs the code and immediately exits. What is the intended way to make python stay running and listening for hotkeys?

Native AHK scripts do this by default, so it might be worth adding this to the readme.

**Comment by mkzeender** [comment]
Hi, glad you like it!

 I have updated the README to reference the ahk.run_forever() function, which does the thing that you want it to, and I have marked this issue as complete. Keep in mind that this API and the docs are currently not complete and are subject to change.
 
 Have a great day!
